/* Tests Boost's mutex, condition variable and permit under heavy load
(C) 2014 Niall Douglas http://www.nedproductions.biz/


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "boost/thread/mutex.hpp"
#include "boost/thread/condition_variable.hpp"
#include "boost/thread/permit.hpp"
#include "boost/thread/thread.hpp"
#include "boost/detail/lightweight_test.hpp"
#include "boost/make_shared.hpp"
#include "boost/bind/bind.hpp"

#include <iostream>

template<class impl> struct test_wait_atomicity
{
    boost::atomic<bool> gate;
    boost::atomic<size_t> ready;
    struct state
    {
        impl i;
        boost::atomic<bool> gate;
        boost::atomic<size_t> signalled, waitenter, waitexit, timedout;
        state() : gate(false), signalled(0), waitenter(0), waitexit(0), timedout(0) { }
    };
    bool operator()(int seconds)
    {
        std::cout << std::endl << std::endl << "Testing " << impl::desc() << " for wait mutex unlock/lock atomicity ..." << std::endl << std::endl;
        gate=false;
        ready=0;
        size_t concurrency=boost::thread::hardware_concurrency();
        if(concurrency<1) concurrency=1;
        std::vector<boost::shared_ptr<state> > states;
        std::vector<boost::shared_ptr<boost::thread> > threads;
        for(size_t n=0; n<concurrency; n++)
        {
            states.push_back(boost::make_shared<state>());
            threads.push_back(boost::make_shared<boost::thread>(boost::bind(&test_wait_atomicity::e, this, states.back(), false)));
            threads.push_back(boost::make_shared<boost::thread>(boost::bind(&test_wait_atomicity::e, this, states.back(), true)));
        }
        while(ready<concurrency)
            boost::this_thread::yield();
        gate=true;
        boost::this_thread::sleep_for(boost::chrono::seconds(seconds));
        for(size_t n=0; n<threads.size(); n++)
            threads[n]->interrupt();
        for(size_t n=0; n<threads.size(); n++)
            threads[n]->join();
        size_t signalled=0, waitenter=0, waitexit=0, timedout=0;
        for(size_t n=0; n<states.size(); n++)
        {
            signalled+=states[n]->signalled;
            waitenter+=states[n]->waitenter;
            waitexit+=states[n]->waitexit;
            timedout+=states[n]->timedout;
        }
        std::cout << "   Of " << signalled << " signals and " << waitenter << " waits, " << timedout << " signals were lost." << std::endl;
        if(timedout!=0)
        {
            std::cout << "   Specifically for these thread pairs:" << std::endl;
            for(size_t n=0; n<states.size(); n++)
                std::cout << "      " << n << ": signalled=" << states[n]->signalled << " waits=" << states[n]->waitenter << " timedout=" << states[n]->timedout << std::endl;
        }
        return timedout==0;
    }
    void e(boost::shared_ptr<state> s, bool notifier)
    {
        ++ready;
        while(!gate)
            boost::this_thread::yield();
        if(notifier)
        {
            // Wait until waiter thread has locked mutex
            while(!s->gate)
                boost::this_thread::yield();
            while(!boost::this_thread::interruption_requested())
            {
                s->i.lock();  // Shouldn't return until wait has begun
                s->i.signal();  // Release the wait
                ++s->signalled;
                size_t waitenter=s->waitenter;
                s->i.unlock();  // Wait shouldn't exit until this line
                // Wait for wait to complete or time out
                while(waitenter!=s->waitexit && !boost::this_thread::interruption_requested())
                    boost::this_thread::yield();
            }
        }
        else
        {
            s->i.lock();
            s->gate=true;  // Release notifier thread now mutex is locked
            try
            {
                while(!boost::this_thread::interruption_requested())
                {
                    ++s->waitenter;
                    // If the waitable really does atomically unlock the mutex
                    // during around the wait, this should never time out.
                    if(!s->i.wait(1000))
                        ++s->timedout;
                    ++s->waitexit;
                }
            }
            catch(const boost::thread_interrupted &)
            { }
            catch(...)
            {
                throw;
            }
            s->i.unlock();
        }
    }
};

struct boost_condvar
{
    static const char *desc() { return "boost::condition_variable"; }
    typedef boost::mutex mutex_t;
    typedef boost::condition_variable waitable_t;
    mutex_t mutex;
    waitable_t waitable;
    // No constructor necessary
    void lock() { mutex.lock(); }
    bool try_lock() { return mutex.try_lock(); }
    void unlock() { mutex.unlock(); }
    bool wait(size_t ms)
    {
        boost::cv_status ret=boost::cv_status::timeout;
        boost::unique_lock<mutex_t> lock(mutex, boost::adopt_lock);
        try
        {
            ret=waitable.wait_for(lock, boost::chrono::milliseconds(ms));
            lock.release();
        }
        catch(...)
        {
            lock.release();
            throw;
        }
        return boost::cv_status::no_timeout==ret;
    }
    void signal()
    {
        waitable.notify_one();
    }
};

int main(int argc, const char *argv[])
{
    if(argc>1 && !strncmp(argv[1], "-h", 2))
    {
        std::cout << "Usage: " << argv[0] << " <seconds of testing per object>" << std::endl;
        return 0;
    }
    int seconds=0;
    if(argc>1) seconds=atoi(argv[1]);
    if(!seconds) seconds=30;

    // steady_clock::now() isn't threadsafe on first use on Windows
    boost::chrono::steady_clock::now();

    BOOST_TEST(test_wait_atomicity<boost_condvar>()(seconds) == true);

#ifdef _MSC_VER
//    std::cout << "Press return to exit" << std::endl;
//    getchar();
#endif
    return 0;
}