/* pthread_permit_validity.cpp
Unit testing for pthread_permit1 and pthread_permit
(C) 2012-2014 Niall Douglas http://www.nedproductions.biz/


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

// Disable the CATCH unit test framework, and redirect to use Boost.Test
#define PTHREAD_PERMIT_DISABLE_CATCH
#include <vector>
#include <boost/detail/lightweight_test.hpp>
static std::vector<std::pair<void (*)(), const char *>> &mytests()
{
  static std::vector<std::pair<void (*)(), const char *>> v;
  return v;
}
struct static_initialiser
{
  static_initialiser(void (*f)(), const char *desc) { mytests().push_back(std::make_pair(f, desc)); }
};
#define TEST_CASE(name, desc) \
  static void TEST_CASE_##__LINE__(); \
  static static_initialiser TEST_CASE_INIT_##__LINE__(&TEST_CASE_##__LINE__, (desc)); \
  static void TEST_CASE_##__LINE__()
#define REQUIRE(stmt) BOOST_TEST(stmt)


#include "boost/thread/permit/unittests.cpp"

int main()
{
  BOOST_THREAD_LOG << BOOST_THREAD_END_LOG;
  {
    for(std::vector<std::pair<void (*)(), const char *>>::const_iterator it=mytests().begin(); it!=mytests().end(); ++it)
    {
      BOOST_LIGHTWEIGHT_TEST_OSTREAM << std::endl << "==== " << it->second << " ====" << std::endl;
      it->first();
    }
  }
  BOOST_THREAD_LOG << BOOST_THREAD_END_LOG;

  return boost::report_errors();
}
